name: Auto Update EPG

on:
  schedule:
    - cron: '0 3 * * *' # Запуск каждую ночь в 03:00
  workflow_dispatch: # Кнопка для запуска вручную

jobs:
  update:
    runs-on: ubuntu-latest
    # Добавляем права на запись, чтобы бот мог пушить файлы
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download EPG
        run: |
          # Используем расширенный curl с User-Agent и повторами
          curl -L -f -s \
          -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" \
          "http://epg.one/pp.xml.gz" -o epg.xml.gz \
          || (echo "Download failed" && exit 1)

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add epg.xml.gz
          # Если файл не изменился, скрипт просто завершится без ошибки
          git commit -m "Daily EPG update: $(date +'%Y-%m-%d')" || exit 0
          git push
